### PR TITLE
Fix ePub viewer code to display math notation

### PR DESCRIPTION
**Pull request by qykth-git**
Current (4.3.0+dfsg-1) `ebook-viewer` breaks when displays math notation. Because current `calibre` package dose not installs MathJax code properly, and provides some errors like:
```
IOError:[Errno 2] No such file or directory: u'/usr/share/calibre/mathjax/manifest.json'
```

This pull request fixes this error.

This pull request includes:
* Install proper symbolic links to point system MathJax code.
* Recover from bad symbolic links that comes from previous package version.

The recover code is done by `dpkg-maintscript-helper(1)` , and use dummy version number to make package update code works. We must provides real version number to release new version package.

### CODE REVIEW

**Comment by norbusan** [comment]
Yokota-san
thanks a lot, that looks excellent. I would like to test it also with an epub, do you have an example epub with math that you could share with me (either in private or here)?

Best

Norbert

**Comment by norbusan** [comment]
I have merged and moved the maintscript code into `debian/calibre.maintscript` instead of adding more files and repeating the code.

The only unclear point is the order in the postinst, but I hope that is fine.

**Comment by qykth-git** [comment]
Last "postinst" change ( 954f86089dcb0a5b3f4231a731d3a03f21643379 ) is just a cosmetic fix.
If something wrong to you, you can revert it.

And here is some minimal test file that uses to make this pull request. You must install `pandoc` to build ePub file.

Copy two files (`pi.md` and `Makefile`) to someware, and type `make` to go.
The error will happen when `ebook-viewer` displays a page that have math notation.
You can alter math notation (`\pi`) with TeX style math notation. Check `pandoc` manual for details.

* pi.md
``` markdown
---
title: book
---

# test
$\pi$
```
* Makefile
``` makefile
.PHONY: run clean

SRC = pi.md
EPUB = $(SRC:.md=.epub)

run: $(EPUB)
	ebook-viewer $<

$(EPUB): $(SRC)
	pandoc -o $@ $<

clean:
	rm -f $(EPUB)
```

**Comment by norbusan** [comment]
Thanks, indeed, I have forgotten about pandoc, that is an easy way to test it, I can reproduce it.

Will upload Py2/Py3 versions to sid/experimental later today. Thanks a lot again!

**Pull request merged**
